import {
  Chat,
  ChatBubbleOutlineOutlined,
  ChatBubbleSharp,
  FacebookOutlined,
  FacebookRounded,
  FacebookSharp,
  HtmlOutlined,
  Instagram,
  MailOutlined,
  MessageOutlined,
  MessageRounded,
  MessageTwoTone,
  PhoneAndroid,
  WhatsApp,
} from '@mui/icons-material';
import {
  Box,
  createTheme,
  CssBaseline,
  Divider,
  Grid,
  Link,
  List,
  ListItem,
  MobileStepper,
  ThemeProvider,
  Typography,
} from '@mui/material';
import { style } from '@mui/system';
import Head from 'next/head';
import Image from 'next/image';
import Conntect from '../compents/Conntect';
import Server from '../compents/Server';
import styles from '../styles/Home.module.css';

export default function Home() {
  const theme = createTheme({
    typography: {
      h1: {
        fontSize: '1.8rem',
        textTransform: 'capitalize',
        fontStyle: 'italic',
        fontWeight: 700,
      },
      h2: {
        fontSize: '1.6rem',
        textTransform: 'capitalize',
        fontStyle: 'italic',
        fontWeight: 700,
      },
    },
  });
  return (
    <div className={styles.container1}>
      <Head>
        <title> mohamed profile</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <section className={styles.top}>
          <container className={styles.container}>
            <div className={styles.logo}>
              <Typography component={'h1'} variant='h1'>
                mohamed dahy
              </Typography>
              <Image
                src={'/image/FB_IMG_1647542712439.jpg'}
                width={200}
                height={200}
                priority
              />
            </div>
            <div className={styles.info}>
              <List>
                <ListItem>
                  <a href='#serves'>Serves</a>
                </ListItem>
                <ListItem>
                  {' '}
                  <a href='#project'>project</a>
                </ListItem>
                <ListItem>
                  {' '}
                  <a href='#aboutme'>about me</a>
                </ListItem>
                <ListItem>
                  {' '}
                  <a href='#contactme'>conntact me</a>
                </ListItem>
              </List>
            </div>
          </container>
        </section>
        <section>
          <div className={styles.about}>
            <div className={styles.aboutText}>
              <Typography component={'h1'} variant='h1'>
                About me{' '}
              </Typography>
            </div>
            <div className={styles.text}>
              <p>
                My name mohamed dahy , Website designer and developer, I have
                experience with html, css, nextjs.
              </p>
              <Link href='/aboutme'> more..</Link>
            </div>
          </div>
        </section>
        <section id='serves' className={styles.server}>
          <div className={styles.serves}>
            <Typography component={'h1'} variant='h1' align='center'>
              server
            </Typography>
          </div>
          <Grid
            container
            spacing={1}
            style={{
              display: 'flex',
              margin: '50px 0px ',
              justifyContent: 'space-around',
            }}
          >
            <Server
              src={
                '/image/17 Simple HTML Code Examples You Can Learn in 10 Minutes.png'
              }
              text='Design and build websites in html'
            />
            <Server
              src={
                'https://i.pinimg.com/564x/a6/38/56/a638560203151081fdd96760a972bb8e.jpg'
              }
              text={
                'Consistent formatting in css to give an aesthetic look to the sites'
              }
            />
            <Server
              src={
                'https://i.pinimg.com/564x/86/ff/86/86ff86b76cd898dee3892740913ac4e8.jpg'
              }
              text={'Use React to design websites professionally and quickly'}
            />
            <Server
              src={
                'https://i.pinimg.com/564x/e8/53/c4/e853c44fcd834f738908f6f9c0eea4fc.jpg'
              }
              text={
                'I can use Nextjs to build commercial websites very professionally'
              }
            />
          </Grid>
        </section>
        <Divider />
        <footer className={styles.footer}>
          <Box className={styles.contactme}>
            <div id='contactme'>
              <Typography component={'h1'} variant='h1'>
                {' '}
                conntact me{' '}
              </Typography>
            </div>
            <div className={styles.icons}>
              <Conntect
                icon={<MailOutlined />}
                text={' mohameddahy111@gmail.com'}
                text2={' mohameddahy111@gmail.com'}
                i={'mailto'}
              />
              <Conntect
                icon={<WhatsApp style={{ color: 'green' }} />}
                i={'tel:'}
                text={'+201092616161'}
                text2={'+201092616161'}
              />
              <Conntect
                icon={<PhoneAndroid />}
                i={'tel:'}
                text2={'+201558987688'}
                text={'+201558987688'}
              />
            </div>
          </Box>
          <Box className={styles.followme}>
            <Typography component={'h1'} variant='h1'>
              Follow me
            </Typography>
            <div>
              <Conntect
                icon={<FacebookSharp style={{ color: 'blue' }} />}
                text2={<Typography>mohameddahy</Typography>}
                i={'http://'}
                text={
                  'www.facebook.com/coktail.eltibe/?notif_id=1646748173030231&notif_t=page_user_activity&ref=notif'
                }
              />
              <Conntect icon={<Instagram />} text2={'mohameddahy11'} />
              <Conntect
                icon={<ChatBubbleOutlineOutlined />}
                text2={'mohameddahy11'}
              />
            </div>
          </Box>
        </footer>
      </ThemeProvider>
    </div>
  );
}
